import Head from "next/head"
import { Box, Flex, Hide } from "@chakra-ui/react"
import Navbar from "../components/navbar"
import Section from "../components/section"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hide below="md">
          <Navbar />
        </Hide>
        <Flex ml={{ base: "0px", md: "200px" }} direction="column">
          <Section title="Home" element="home">
            <Box w="200px" bg="white" h="1000px"></Box>
          </Section>
          <Section title="About Me" element="about">
            <Box w="200px" bg="white" h="100px"></Box>
          </Section>
          <Section title="Projects" element="projects">
            <Box w="200px" bg="white" h="1000px"></Box>
          </Section>
        </Flex>
      </main>
    </>
  )
}
